app = "hydrogen"
primary_region = "cdg"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1

[env]
  URL="https://cesium.di.uminho.pt"
  NEXT_PUBLIC_CURRENT_MANDATE="2024-2025"
