name: CI Style

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup up Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.11.1

      - name: Setup up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.30

      - name: Install dependencies
        run: bun i

      - name: Format the code
        run: bun format

      - name: Lint the code
        run: bun run lint
