name: Code Quality

on:
  pull_request:
    branches: [main, develop]
    types: [opened, synchronize]

jobs:
  style:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["18.12.0"]

    steps:
      - name: ☁ Checkout code
        uses: actions/checkout@v2

      - name: 📬 Caching
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: 🟩 Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: 🧰 Install dependencies
        run: npm ci

      - name: 🎨 Check code formatting
        run: npm run test:format

      - name: 🐛 Lint the code
        run: npm run test:lint
